id: P05A5A588
initial_creation_type: ocr
source_metadata:
  volumes:
    f75dfabde76c4e53a084fa016c1c64b0:
      base_file: v065.txt
      image_group_id: I1PD95910
      title: འཕགས་པ་ཆོས་བཞི་པའི་རྣམ་པར་བཤད་པ།
      total_pages: 1498
      volume_number: 65
